### ISSUE TITLE
Provide Jetty images based on openjdk:11-jre-slim

### ISSUE THREAD

**Issue by wenslayer** [appropriate/docker-jetty#103]
I see the current [jre-11 based Jetty image](https://github.com/appropriate/docker-jetty/blob/1ee7404fbd6c692000ab6fbeb1621ad6280d69ed/9.4-jre11/Dockerfile) is based off [openjdk:11-jre](https://github.com/docker-library/openjdk/blob/df4cff5b79d52fa311d6dff4c874f191996b583c/11/jre/Dockerfile).

To reduce image size, it would be valuable if Jetty images existed that were based off the [openjdk:11-jre-slim](https://github.com/docker-library/openjdk/blob/df4cff5b79d52fa311d6dff4c874f191996b583c/11/jre/slim/Dockerfile) image.

Thank you for your consideration.

**Comment by gregw** [comment]
@md5 I'm guessing we should just make another variant rather than make everybody use slim?
@wenslayer I'm currently on vacation, so wont get around to this for a few weeks.... but if you wanted to prepare a PR, then I can review and merge if it checks out.

**Comment by md5** [comment]
> @md5 I'm guessing we should just make another variant rather than make everybody use slim?

Yeah, I think this would be another variant. It makes sense to me, given the lack of a JDK 11 for Alpine for the time being.

**Comment by tianon** [comment]
At this point this should probably be co-opted to account for https://github.com/docker-library/openjdk/pull/322. :disappointed:

**Comment by gregw** [comment]
@tianon can you comment a bit more on the implications of docker-library/openjdk#322 ?

Also, I think it is time to look at jkd13... there are currently slim and buster varieties of that.

**Comment by gregw** [comment]
The merge of #121 created the slim images, but has broken the architecture rules.

**Comment by gregw** [comment]
https://github.com/docker-library/official-images/pull/7134

**Comment by joakime** [comment]
This issue has been moved to the new Official Eclipse Jetty Docker repository.

See https://github.com/eclipse/jetty.docker/issues/6
