### ISSUE TITLE
jetty user home is not properly set

### ISSUE THREAD

**Issue by surli** [appropriate/docker-jetty#106]
Current jetty images leaves the default home for the jetty user (i.e. /home/jetty) which might lead to various errors when building a custom image from it. 

The error is easy to reproduce : 
```
[urli@vivat ~]$ docker run -it jetty:latest /bin/bash
jetty@c48a79115c75:/var/lib/jetty$ cd
bash: cd: /home/jetty: No such file or directory
```

**Comment by gregw** [comment]
Happy to define the home directory.... just wondering if it should be `$JETTY_HOME` or `$JETTY_BASE`?   I'm leaning towards `$JETTY_BASE`.

**Comment by surli** [comment]
IMO it would be less surprising for users to have `$JETTY_HOME` as the jetty user home directory.

**Comment by gregw** [comment]
I'm looking for other examples in unix.  gdm home is `/var/lib/gdm3` and not `/usr/lib/gdm3/` where the code lives.  `$JETTY_HOME` is equivalent to usr directory and `$JETTY_BASE` is the /var directory in which you expect to make modifications.

... yes they should have been named the other way around...

**Comment by surli** [comment]
ahah indeed :) so I guess a good compromise might be to indeed use JETTY_BASE as home dir, and to document it in https://docs.docker.com/samples/library/jetty/#environment

**Comment by joakime** [comment]
This issue has been moved to the new Official Eclipse Jetty Docker repository.

See https://github.com/eclipse/jetty.docker/issues/106
