### ISSUE TITLE
Docker image for jetty 10

### ISSUE THREAD

**Issue by chergey** [appropriate/docker-jetty#109]
Hi,
Are there plans to dockerize jetty 10 ?  I tried to replace JETTY_TGZ_URL url in https://github.com/appropriate/docker-jetty/blob/master/9.4-jre11/Dockerfile for jetty 10 but image creation fails with error: 

> *+* gpg --batch --verify jetty.tar.gz.asc jetty.tar.gz
gpg: Signature made Thu 11 Jul 2019 12:21:30 PM UTC using DSA key ID B4372146
gpg: Can't check signature: No public key

**Comment by joakime** [comment]
Where did you get the image of jetty.tar.gz and jetty.tar.gz.asc?

That key isn't recognized by the the list of keys at
https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/KEYS.txt

**Comment by chergey** [comment]
From [here](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-home/10.0.0-alpha0/jetty-home-10.0.0-alpha0.tar.gz). Why is it not recognized ? It this version being developed by other people ?

**Comment by joakime** [comment]
This issue has been moved to the new Official Eclipse Jetty Docker repository.

See https://github.com/eclipse/jetty.docker/issues/11
