### ISSUE TITLE
Discontinue building the image based on OpenJDK JRE 7 

### ISSUE THREAD

**Issue by vutny** [appropriate/docker-jetty#117]
Although OpenJDK still maintains some JRE/JDK 7 [code updates](https://hg.openjdk.java.net/jdk7u), the latest and greatest ready-to-consume builds are exclusively provided to [RedHat subscribers](https://access.redhat.com/articles/1299013).

Last time the binary package of 7u231 version was available in Debian "jessie" (*oldoldstable*) at [2019-08-22](https://tracker.debian.org/pkg/openjdk-7) (7u231). But there are still 14 pending security vulnerabilities. 
The official Docker images of `openjdk:7-jre` have not been updated since the merge of docker-library/openjdk#322 almost 6 months ago. 

I think it is the time to stop supplying Jetty 9.2 images based on outdated OpenJDK and base operating system. The latest release was `9.2.29.v20191105`, which works on **JRE 8**, but the EOL was [declared last year](https://www.eclipse.org/lists/jetty-announce/msg00116.html).

Considering all of that I think we could safely remove `9.2-jre7` directory from this repo. The images are still on Docker Hub for whoever needs them.

**Comment by gregw** [comment]
Fixed with #118
