### ISSUE TITLE
Update docs to highlight Jetty 9.3 functionality

### ISSUE THREAD

**Issue by md5** [appropriate/docker-jetty#13]
Particularly HTTP/2 support

**Comment by zebehringer** [comment]
I was unable to get the http/2 module running with the latest 9.3 image as-is. I ended up getting it to run by manually installing an ALPN module in a mounted volume (JETTY_BASE), based on the info provided here: https://webtide.com/http2-on-google-compute-engine-with-jetty/

Below are the actual steps I used. I imagine someone with more docker experience could simplify this script a little, but I would assume that the ultimate goal would be to have this done by the dockerfile.

```
# copy JETTY_HOME volume from the last jetty:9 image container, replacing e337d9 with the container's id-ish
docker cp e337d9:/usr/local/jetty .
# create folder for ALPN module definition
mkdir -p /ecs/jetty_base/modules/alpn-impl
# copy an ALPN module definition to the folder mounted to JETTY_BASE (in this case /ecs/jetty_base)
sudo cp ./jetty/modules/alpn-impl/alpn-1.8.0_45.mod /ecs/jetty_base/modules/alpn-impl/alpn-1.8.0_45-internal.mod
# cause jetty to install/download ALPN module jar (a dependency of http2 module) into JETTY_BASE/libs
docker run -v /ecs/jetty_base:/var/lib/jetty jetty:9 java -jar /usr/local/jetty/start.jar --create-files

#now jetty can be run with http2 module
```

disclaimer: I haven't actually tried to make an http/2 connection to this server yet, but at least I can get it running without jetty complaining about the missing ALPN dependency

**Comment by md5** [comment]
This blog post has a better description of the actual issue: http://devtidbits.com/2015/06/23/jetty-9-3-http2-dependancy-issue-with-ubuntu-14-04/

It looks like the problem is that the `openjdk-8-jre-headless` package may have been based on an unstable/developer build of OpenJDK, hence the `-internal` qualifier on the version number.

I'm not sure whether I consider this a Debian bug or a Jetty bug, but it doesn't look like it's been reported in the Jetty issue tracker. I'm a bit leery of fixing this in the Docker image, since it has nothing to do with Docker and will occur for anyone using `openjdk-8-jre-headless` on any platform, not just Docker or GCE (e.g. the blog post I referenced above is using Ubuntu 14.04).

@gregw I'd be curious to get your thoughts about this. I can add something to the Dockerfile to go create a bunch of `*-internal.mod` symlinks, but it seems like a fix in the Jetty packaging would be preferable.

**Comment by zebehringer** [comment]
That link helps answer some questions I had (the "-internal" qualifier, mainly), thanks!

I think I would now agree that changing your docker image would not be the ideal solution.
I am running now, and have an easy hack solution, even if it isn't 100% dockerized, so I'm content.

**Comment by md5** [comment]
I believe adding a line like this to the Dockerfile would fix things:

``` Dockerfile
RUN VERSION=$(java -version 2>&1 | awk -F'"' 'NR == 1 { print $2 }') \
    && cd $JETTY_HOME/modules/alpn-impl
    && ln -s alpn-${VERSION%-internal}.mod alpn-$VERSION.mod
```

It should probably be modified to skip linking the `*.mod` file if the version doesn't end with `-internal`.

**Comment by gregw** [comment]
@md5  I agree we should do better:  https://bugs.eclipse.org/bugs/show_bug.cgi?id=474361

**Comment by zebehringer** [comment]
I'll give that a shot, thanks!

**Comment by joakime** [comment]
@md5 you don't have to modify the alpn files.

Just pass the java.version on the command line. aka ...

```
$ java -jar /path/to/jetty-dist/start.jar java.version=1.8.0_45
```

That will work right now.

(Its how we test alternate java versions, even ones we don't have ourselves)

Meanwhile, we'll fix this in start.jar itself.

**Comment by md5** [comment]
@joakime The problem is that there isn't a straightforward way for me to get the string "1.8.0_45" other than parsing the output of `java -version` and stripping the `-internal`. The other alternative would be to munge the package version "8u45" into "1.8.0_45", which seems a bit too hacky to me.

Also, my proposed workaround wasn't to modify the `alpn-impl` files, but rather to symlink the existing `alpn-1.8.0_45.mod` as `alpn-1.8.0_45-internal.mod`.

**Comment by md5** [comment]
One more thing I'll mention is that there seems to be a proposal for Java 9 to standardize `java.version` strings here: http://openjdk.java.net/jeps/223

**Comment by joakime** [comment]
The JEP 223 is a welcome news.   Looking forward to it.
We've implemented some java.version sanitation in [master] branch yesterday, it will be available in the next Jetty 9.3.x release.

**Comment by md5** [comment]
:+1:​

**Comment by zebehringer** [comment]
I put -Djava.version=1.8.0_45 in my start.ini file, and that seems to work.
One catch, though, is that I still have to run start.jar with the --create-files option to get the ALPN lib downloaded to $JETTY_BASE/lib/alpn before I can run with the http2 module. Should the dockerfile take care of that for me?

**Comment by md5** [comment]
@zebehringer Could you be more specific about the error you're seeing and how you're getting it?

I just ran this command:

```
docker run -it --rm jetty:9.3 sh -c 'java -jar $JETTY_HOME/start.jar --add-to-startd=http2 -Djava.version=1.8.0_45'
```

And I wasn't given an error about `--create-files`. After running that command, I see a `lib/alpn` directory under `$JETTY_BASE`, so I'm not sure what issue you're running into.

One thing that did happen, however, is that I was prompted to acknowledge a license exception.

@joakime Is there a way to pre-accept the license for ALPN so that we can document the process for users? I think the licensing thing may complicate publishing a pre-baked Docker image that already has `http2` enabled, but it shouldn't prevent those using private Docker images from automatically accepting the license when they're doing so on behalf of themselves or their company for internal distribution.

**Comment by joakime** [comment]
As long as the file is in place then the license check/question does not pop up.

But if you still want to use the `--create-files` command line,
then you can also add `--approve-all-licenses` to not have the ack on licenses occur.

**Comment by md5** [comment]
> As long as the file is in place then the license check/question does not pop up.

I'm not sure what you mean. Don't I need to I run the `--add-to-startd=http2` command to install the module and its dependencies? When I do that, the license prompt comes up. Are you suggesting adding the ALPN dependencies manually or something?

**Comment by md5** [comment]
BTW, thanks for the `--approve-all-licenses` tip.

**Comment by zebehringer** [comment]
I was just setting up the following start.ini file in mounted volume mapped to /var/lib/jetty.

```
--module=http2
-Djava.version=1.8.0_45
```

and here are the logs where it complains about missing files:

```
Running Jetty:
2015-08-10 15:25:34.094:INFO::main: Logging initialized @165ms
2015-08-10 15:25:34.520:INFO:oejs.Server:main: jetty-9.3.2.v20150730
2015-08-10 15:25:34.641:INFO:oejus.SslContextFactory:main: x509={jetty.eclipse.org=jetty} wild={} alias=null for SslContextFactory@63e31ee(file:///var/lib/jetty/etc/keystore,file:///var/lib/jetty/etc/keystore)
2015-08-10 15:25:34.854:INFO:oejs.ServerConnector:main: Started ServerConnector@6574c6f{SSL,[ssl, alpn, h2, h2-17, h2-16, h2-15, h2-14]}{0.0.0.0:8443}
2015-08-10 15:25:34.854:INFO:oejs.Server:main: Started @929ms
Running Jetty:
WARNING: Missing Required File: ${jetty.base}/lib/alpn/alpn-boot-8.1.3.v20150130.jar
WARNING:   Can be downloaded From: http://central.maven.org/maven2/org/mortbay/jetty/alpn/alpn-boot/8.1.3.v20150130/alpn-boot-8.1.3.v20150130.jar
WARNING:   Run start.jar --create-files to download
WARNING: Missing Required File: ${jetty.base}/etc/keystore
WARNING:   Can be downloaded From: http://git.eclipse.org/c/jetty/org.eclipse.jetty.project.git/plain/jetty-server/src/test/config/etc/keystore?id=master
WARNING:   Run start.jar --create-files to download
MKDIR: ${jetty.base}/lib
MKDIR: ${jetty.base}/lib/alpn
INFO: Base directory was modified
```

I did run your suggested command with the --add-to-startd=http2 stuff, and that worked, plus it created some start.d files that I probably need anyway. I will go with that solution for setting up http2 instead of --module=http2.

**Comment by joakime** [comment]
@zebehringer just a note, `--add-to-start=http2` is far more common usage than `--add-to-startd=<name>` (note the lack of `d`)

**Comment by md5** [comment]
Hi all. I had some time this evening to rework the docs. Please take a look: https://github.com/docker-library/docs/compare/master...appropriate:jetty-document-http2

The `http2`-related commands documented in that branch will only work once the changes from https://github.com/eclipse/jetty.project/commit/d02a5c3c8bbf3fe05b262125358677847b303688 make it into a Jetty 9.3 release. I'll open a PR against `docker-library/docs` once I've updated the `jetty` image for that forthcoming release.

**Comment by md5** [comment]
@joakime The reason I used `--add-to-startd` in the `Dockerfile` is to avoid any potential conflicts with user-provided `start.ini` files.

Was that a bad idea?

**Comment by md5** [comment]
FWIW, I just tried testing it in Chrome and it didn't seem to work... :grimacing: 

Instead, it still connected with TLS 1.2. I tried testing with `curl`, but I don't have a `curl` with HTTP/2 support handy.

**Comment by gregw** [comment]
@md5 I actually prefer startd style over start.ini and I use that style when I can.  Having said that there are a few bugs with startd in 9.2, which has forced me to use start.ini, but they are fixed in 9.3

The two styles should be equivalent and simply a matter of taste.

**Comment by md5** [comment]
I just submitted a PR to the docs: https://github.com/docker-library/docs/pull/353

I would have submitted this sooner, but I didn't realize the Jetty 9.3.3 was released since it doesn't appear to have been announced on the `jetty-announce` mailing list.

**Comment by gregw** [comment]
Ooops - our bad!

9.3.4 is about a week or 3 away.

cheers

On 1 October 2015 at 15:19, Mike Dillon notifications@github.com wrote:

> I just submitted a PR to the docs: docker-library/docs#353
> https://github.com/docker-library/docs/pull/353
> 
> I would have submitted this sooner, but I didn't realize the Jetty 9.3.3
> was released since it doesn't appear to have been announced on the
> jetty-announce mailing list.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/appropriate/docker-jetty/issues/13#issuecomment-144621878
> .

## 

Greg Wilkins gregw@webtide.com CTO http://webtide.com

**Comment by md5** [comment]
https://github.com/docker-library/docs/pull/353 has been merged.

Looking at those docs made me realize we're not giving any guidance on configuring the SSL key and certificates, so I opened #20 to track that.

**Comment by md5** [comment]
Thanks @zebehringer for helping to sort out the `java.version` thing! :+1:
