### ISSUE TITLE
Container exits immediately when using JDWP in JAVA_OPTIONS

### ISSUE THREAD

**Issue by milo2048** [appropriate/docker-jetty#130]
Running with docker-compose, using jetty:9.4-jre8, when I specify this:
```
environment:
     JAVA_OPTIONS=-Xmx2048m -Xms2048m -XX:MaxPermSize=512m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005

```
The Jetty container exits immediately with code 0.  Removing the -agentlib causes it to run normally.

**Comment by milo2048** [comment]
I checked out the latest code and rebuilt the image using docker-entrypoint.sh from commit 6938dbcf3c3f1e433fca63909400670a52f39dfe but otherwise using the code in master.  The new image worked as expected.  This leads me to believe the issue is with the latest entrypoint script.

**Comment by ngvtsn** [comment]
Same. Looks like `docker-entrypoint.sh --dry-run` generates wrong jetty.start

**Comment by sittingbool** [comment]
Same here, how can i resolve this?

**Comment by joakime** [comment]
This issue has been moved to the new Official Eclipse Jetty Docker repository.

See https://github.com/eclipse/jetty.docker/issues/12
