### ISSUE TITLE
Jetty on top of Openjdk-8 JDK version

### ISSUE THREAD

**Issue by PhantomYdn** [appropriate/docker-jetty#131]
Hello!
Is it possible to make an image with openjdk-8, but JDK version (not JRE - as it's right now)?
It would be much more convenient for our project. 

A little more about use case:  our application [Orienteer](https://github.com/OrienteerBAP/Orienteer) is based on [OrientDB](https://github.com/orientechnologies/orientdb) version 2 - which require Java 8. It's running on JRE, but from time to time we need to do more deeper analysis of running instance with the aid of `jcmd` and etc. But we can't do it on top of JRE version.

**Comment by PhantomYdn** [comment]
PR created #132

**Comment by joakime** [comment]
This issue has been moved to the new Official Eclipse Jetty Docker repository.

See https://github.com/eclipse/jetty.docker/issues/13
