### ISSUE TITLE
Add jetty 9 images based on AdoptOpenJDK

### ISSUE THREAD

**Issue by rofrance** [appropriate/docker-jetty#133]
Hi,

I would like to know if it's possible to create images based on AdoptOpenJDK instead of the Oracle OpenJDK.

AOJDK Dockerfiles are available here:
https://hub.docker.com/_/adoptopenjdk?tab=description

This would make sure that our devs don't need to build their own Dockerfiles for Jetty and instead rely on the official images available in this repo.

Thanks for your consideration,
Roberto

**Comment by joakime** [comment]
This issue has been moved to the new Official Eclipse Jetty Docker repository.

See https://github.com/eclipse/jetty.docker/issues/14
