### ISSUE TITLE
Stop supporting deprecated versions of Jetty

### ISSUE THREAD

**Issue by joakime** [appropriate/docker-jetty#135]
Please deprecate and remove listed versions of Jetty that are no longer supported.

See: https://www.eclipse.org/jetty/documentation/current/what-jetty-version.html

All versions of 9.3.x and 9.2.x are deprecated and no longer supported.
The docker images as well should no longer be updated and even listed on hub.docker.com as supported tags.

**Comment by gregw** [comment]
@joakime really?   While there is no intention to maintain and upgrade those images, preserving them for durable builds is desirable.  We don't remove 9.2 and 9.3 from maven central so why should we remove them from official images?     Let's research what the policy is for other docker official images.

**Comment by joakime** [comment]
I'm not saying remove the images from hub.docker.com, i'm saying remove them from the "supported tags" document shown https://hub.docker.com/_/jetty

We still have Jetty 7 <sup>(1)</sup> and Jetty 8 <sup>(2)</sup> images around, but we don't say they are supported.

1. https://hub.docker.com/_/jetty?tab=tags&page=1&ordering=-last_updated&name=7
2. https://hub.docker.com/_/jetty?tab=tags&page=1&ordering=-last_updated&name=8

**Comment by gregw** [comment]
OK, so we need to create a PR against https://github.com/docker-library/docs/tree/master/jetty
I'll do that.

**Comment by gregw** [comment]
Hmmm that section of the README.md is auto generated.    So not sure how we do this short of just removing 9.2 and 9.3

**Comment by joakime** [comment]
This issue has been moved to the new Official Eclipse Jetty Docker repository.

See https://github.com/eclipse/jetty.docker/issues/15
