### ISSUE TITLE
Move official docker-jetty project to the jetty project 

### ISSUE THREAD

**Issue by gregw** [appropriate/docker-jetty#136]
It has been fantastic that jetty-docker was created and maintained by appropriate, but I think it now is falling a little into the cracks between appropriate, eclipse and webtide.
It would probably be better maintained and more responsive if moved either to the jetty project itself or to webtide (the primary maintainer of jetty).

**Comment by joakime** [comment]
This issue has been moved to the new Official Eclipse Jetty Docker repository.

See https://github.com/eclipse/jetty.docker/issues/16

**Comment by WalkerWatch** [comment]
@md5 As part of the migration, Eclipse is sure to reach out for permission/legalese regarding this contribution/movement of code to their repo. To get ahead of that, is there any chance you can fill out an [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)?

**Comment by lachlan-roberts** [comment]
There has now been a release from [eclipse/jetty.docker](https://github.com/eclipse/jetty.docker), and https://hub.docker.com/_/jetty now points to the eclipse repository as well.

So as a final step in this repository, all issues which have been migrated to [eclipse/jetty.docker](https://github.com/eclipse/jetty.docker) should be closed and the project should be marked as archived.
