### ISSUE TITLE
jetty 9.4.29 released

### ISSUE THREAD

**Issue by acutus** [appropriate/docker-jetty#137]
Hi,

Newer versions of jetty 9.4 (jetty-9.4.28.v20200408 and jetty-9.4.29.v20200521) have been released. I was wondering if we could get tags for those (or just .29) in the official images?

**Comment by joakime** [comment]
This issue has been moved to the new Official Eclipse Jetty Docker repository.

See https://github.com/eclipse/jetty.docker/issues/17
