### ISSUE TITLE
JETTY_BASE chown is missing -R

### ISSUE THREAD

**Issue by gregw** [appropriate/docker-jetty#18]
The chown of JETTY_BASE is missing -R, so it's contents are still own by root

**Comment by gregw** [comment]
I'll just wait for an OK before I push the fix to this.... just in case I've got the rough end of the pineapple again:)

**Comment by md5** [comment]
Good catch. I'm assuming you're going to move the `chown` after the `--add-to-startd` line as well so that the contents are actually there to `chown` (instead of an empty directory).

**Comment by gregw** [comment]
I moved the chown to be part of the later one.

**Comment by md5** [comment]
LGTM
