### ISSUE TITLE
Upgrade to Jetty 9.3.7.v20160115

### ISSUE THREAD

**Issue by zlogic** [appropriate/docker-jetty#24]
Would it be possible to upgrade to the latest jetty 9.3.7.v20160115?
Some of the updated features include a fix for the SLOTH vulnerability: https://github.com/eclipse/jetty.project/commit/0a1b0b2bc69ea7e7f5f44992f47a84f926cdeebb

**Comment by md5** [comment]
I've opened #25 with the update. I'll create a PR for `docker-library/official-images` once the tests run.

Thanks for the heads-up! :+1:

**Comment by md5** [comment]
See https://github.com/docker-library/official-images/pull/1426 to track the status of getting an updated image pushed.

**Comment by md5** [comment]
The `jetty:9.3.7` image has been pushed to Docker Hub.
