### ISSUE TITLE
Docker quick fail on web exception

### ISSUE THREAD

**Issue by chrislovecnm** [appropriate/docker-jetty#30]
Hi all

The use case is to have the docker stop when when the default webapp cannot talk to say mysql.

It is my understanding that the following xml is what I need:

```
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_0.dtd">
<Configure class="org.eclipse.jetty.webapp.WebAppContext">
     <!-- don't use the following two lines in the jetty-web.xml -->
         <Set name="war"><SystemProperty name="jetty.home" default="."/>/apollobit-web-0.3.war</Set>
     <Set name="contextPath">/</Set>
     <Set name="throwUnavailableOnStartupException">true</Set>
</Configure>
```

Here is what I have tried:
1. added jetty-web.xml to root.war ... no joy without the name="war" or contextPath
2. added apollobit-web.xml under /var/lib/jetty/webapps no joy

ideas?

**Comment by md5** [comment]
@chrislovecnm The answer here looks reasonable: http://stackoverflow.com/a/16158366/1106808

It looks like you may want to set `startWithUnavailable` to `false` for the `ServletHandler` as well.

Also, it's not clear to me whether you renamed `apollobit-web-0.3.war` to `root.war` in your initial test or what. Another thing that stuck out to me is that you're using `jetty.home` instead of `jetty.base` in your config.

@gregw likely has a more definitive answer, since I'm more familiar with the Docker part of things than the nuances of Jetty configuration.

**Comment by chrislovecnm** [comment]
@md5 forgot to mention that if I do a setThrowUnavailbleException(true) in an embedded server it works fine. Wondering if I need to use jetty-runner.jar

To clarify. Used apollobit-web.xml with the war named the same. Used root.war with a jetty-web.xml file.

**Comment by chrislovecnm** [comment]
@md5 adding the `startWithUnavailable` did not help either ...

**Comment by chrislovecnm** [comment]
So using jetty-runner.jar worked, but I would rather use this docker instead of maintaining our own version of jetty-runner

**Comment by md5** [comment]
@chrislovecnm Did you see `UnavailableException` being thrown in your logs?

It sounds like the issue may be that `start.jar` doesn't exit when one of the installed webapps throws `UnavilableException`.

**Comment by md5** [comment]
BTW, I found that `startWithUnavailable` defaults to `false`, so setting it shouldn't be expected to have any effect.

**Comment by chrislovecnm** [comment]
So it sounds like I need to use jetty-launcher ...

**Comment by md5** [comment]
Is jetty-launcher yet another thing besides jetty-runner? I'd wait to see
what @gregw says before deciding not to use the Docker image. @joakime may
also have some advice. I also wouldn't jump to conclusions right before a
holiday weekend.

**Comment by chrislovecnm** [comment]
Sorry typo ... jetty-runner.jar

**Comment by chrislovecnm** [comment]
Appreciate the help btw!!!

**Comment by chrislovecnm** [comment]
Using `jetty-runner.jar` instead of Docker ... closing.

**Comment by Bill** [comment]
@chrislovecnm is there a modern (9.x) version of `jetty-runner.jar`? I see only up to 8.x. [jetty-runner versions](http://mvnrepository.com/artifact/org.mortbay.jetty/jetty-runner)

Out of curiosity: when you moved to `jetty-runner` did you start `FROM` the official `maven` image to bootstrap it? Care to share your (redacted) POM and `Dockerfile`?

**Comment by joakime** [comment]
mvnrepository.com is bad place to look for maven artifacts, its often wrong, missing information, and even includes information outside of the central repository system.

use http://search.maven.org/ instead (its the official search, is used by eclipse and intellij too, and is maintained by the maven repository maintainers)

that being said, jetty-runner.jar moved to the eclipse.org a while back.

here's the various versions you have available - http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.eclipse.jetty%22%20AND%20a%3A%22jetty-runner%22

**Comment by chrislovecnm** [comment]
@bill you figure it out?

**Comment by md5** [comment]
@chrislovecnm @Bill Do you mind taking your discussion to email since you're talking about _not_ using this Docker image?
