### ISSUE TITLE
ALPN is not correctly selected due to java version with -

### ISSUE THREAD

**Issue by gregw** [appropriate/docker-jetty#31]
If ALPN is enabled, the correct module is not selected because the docker jvm has -internal in the version name.  A [PR has been raised on Jetty](https://github.com/jetty-project/jetty-alpn-agent/pull/3) to make our parsing more lenient, but we have also raised an [issue on docker-java](https://github.com/docker-library/openjdk/issues/72) because GA releases should not have - in their version numbers.

This issue is opened here just to note the ALPN problem and can be closed once jetty version is upgraded or docker-jetty changes.

**Comment by md5** [comment]
I believe this has been fixed for a year or so.
