### ISSUE TITLE
jetty docker usage

### ISSUE THREAD

**Issue by jeremypumphrey** [appropriate/docker-jetty#35]
I'm trying to use jetty to deploy a 1.7 war file. My Dockerfile has only this:
FROM jetty:jre7
ADD  target/match-rules.war /var/lib/jetty/webapps/

The docker container starts
95fcb5134f70        matchbox/nci-match-rules   "/docker-entrypoint.s"   15 seconds ago      Up 14 seconds       0.0.0.0:8080->8080/tcp, 0.0.0.0:10250->10250/tcp   Rules

Is this correct or should I copy the CMD line from the jetty Dockerfile as well? I'm having a problem with the war extraction, but it might be unrelated to the Docker usage.  

2016-06-20 15:02:21.631:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:/var/lib/jetty/webapps/] at interval 1
2016-06-20 15:02:29.313:WARN:oejw.StandardDescriptorProcessor:main: Could not instantiate listener org.jboss.resteasy.plugins.server.servlet.ResteasyBootstrap
java.lang.ClassNotFoundException: org.jboss.resteasy.plugins.server.servlet.ResteasyBootstrap
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
 ...
2016-06-20 15:02:29.687:INFO:nci-match-rules:main: No Spring WebApplicationInitializer types detected on classpath
15:02:29,773 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
15:02:29,773 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]

**Comment by md5** [comment]
You don't need to add a `CMD` line to your own Dockerfile. These lines look suspect:

> 2016-06-20 15:02:29.313:WARN:oejw.StandardDescriptorProcessor:main: Could not instantiate listener org.jboss.resteasy.plugins.server.servlet.ResteasyBootstrap
> java.lang.ClassNotFoundException: org.jboss.resteasy.plugins.server.servlet.ResteasyBootstrap
> at java.net.URLClassLoader$1.run(URLClassLoader.java:366)

**Comment by mmorejon** [comment]
I have the same problem. Any suggestion?

**Comment by joakime** [comment]
This issue has been moved to the new Official Eclipse Jetty Docker repository.

See https://github.com/eclipse/jetty.docker/issues/4
