### ISSUE TITLE
docker_entrypoint script incorrectly inserts the tmpdir property

### ISSUE THREAD

**Issue by gregw** [appropriate/docker-jetty#38]
The current CMD has `-jar start.jar` before `-Djava.io.tmpdir=...`.  This forces start.jar to always fork a new JVM.

We should consider putting the -D first, so a new JVM is only required if a module is enabled that needs additional JVM args (eg ALPN).

**Comment by gregw** [comment]
This issue is a misunderstanding!  The issue pointed at by @md5 was not that the `-D` was after the `-jar start.jar`, but that in the entry point it is between the `-jar` and the `start.jar`.  That is just broken!

**Comment by md5** [comment]
It looks like it's actually not broken...

If you look at the source for the `java` command, it doesn't strictly check that the JAR file name comes after `-jar`. All it does is check that there is at least one argument after `-jar`, but it doesn't immediately capture that argument as the JAR file name. When it finds `-jar` and sees that there are still arguments after it, it continues in a loop that checks for arguments starting with `"-"`. If it sees them, it processes them as normal. Then, when it finds the first argument that doesn't start with `"-"`, the first of _those_ arguments is treated as the JAR file name.

See here: https://github.com/openjdk-mirror/jdk/blob/d564b7c51ace5e0e1dbf3bb2f50483f0648529d2/src/share/bin/java.c#L1072

**Comment by gregw** [comment]
whew! I knew I had tested that functionality!      So not broken, but not desirable either.

**Comment by md5** [comment]
I'm working on a PR

**Comment by md5** [comment]
Fixed in https://github.com/appropriate/docker-jetty/pull/39
