### ISSUE TITLE
Can't set extended attributes on derived image

### ISSUE THREAD

**Issue by el-chogo** [appropriate/docker-jetty#42]
As suggested in #41 I derived an image from `jetty` with the following Dockerfile:

```
FROM jetty:alpine
RUN set -xe \
    && apk add --no-cache --virtual .build-deps attr \
    && setfattr -n user.pax.flags -v "em" /usr/lib/jvm/java-1.8-openjdk/jre/bin/java \
    && apk del .build-deps \
    && rm -rf .build-deps \
    && rm -rf /tmp/hsperfdata_root
```

Once build is completed, java binary has no extended attributes. If I start an interactive session and set them manually they do work though.

I'm using docker with devicemapper loop sparse files and XFS as backing filesystem (as reported by `docker info`).

Any hint would be appreciated ;).

**Comment by md5** [comment]
Does `getfattr` show the attributes?

**Comment by md5** [comment]
This looks related: https://github.com/docker/docker/issues/23125

**Comment by el-chogo** [comment]
Yeah, apparently those attributes need to be set at container run time. I will do so, as the other workaround (adding ELF exception markers through `paxctl`) doesn't work on my distro (ArchLinux).
