### ISSUE TITLE
Running docker-jetty  on mac

### ISSUE THREAD

**Issue by stevensouza** [appropriate/docker-jetty#47]
New to docker, so may be missing something obvious but i can't get this image to serve pages on my mac.  Any help is appreciated.

1) I run the following from my mac:
docker run -d jetty

2) And then the following to get the container-ip:
docker-machine ip

3) And then put the following on my macs chrome browser:
http://container-ip:8080/

I get the following message in the browser: This site can’t be reached

4) I execute docker logs container-name and everything looks ok;
2016-08-26 18:52:18.836:INFO::main: Logging initialized @791ms
2016-08-26 18:52:19.166:INFO:oejs.SetUIDListener:main: Setting umask=02
2016-08-26 18:52:19.229:INFO:oejs.SetUIDListener:main: Opened ServerConnector@6108b2d7{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2016-08-26 18:52:19.229:INFO:oejs.SetUIDListener:main: Setting GID=999
2016-08-26 18:52:19.236:INFO:oejs.SetUIDListener:main: Setting UID=999
2016-08-26 18:52:19.241:INFO:oejs.Server:main: jetty-9.3.10.v20160621
2016-08-26 18:52:19.262:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:///var/lib/jetty/webapps/] at interval 1
2016-08-26 18:52:19.304:INFO:oejs.AbstractConnector:main: Started ServerConnector@6108b2d7{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2016-08-26 18:52:19.304:INFO:oejs.Server:main: Started @1259ms

**Comment by md5** [comment]
The IP address you get from `docker-machine ip` is not a container IP, but rather the IP address of the Linux VM running the Docker daemon. This is a different IP address from the container's IP address, which is isolated to an internal bridge network within the VM and not accessible from your Mac.

If you want to access the Jetty service from your Mac, you'll need to publish the port the the VM's IP address by adding `-p 8080:8080` to your `docker run` command.

You may also want to investigate using [Docker for Mac](https://docs.docker.com/docker-for-mac/) instead of `docker-machine` from the Docker Toolbox. This will make it so that `-p 8080:8080` exposes the container at http://localhost:8080 instead of `http://VM_IP_ADDRESS:8080`

Docker for Mac is a newer way of running Docker on a Mac that uses `xhyve` instead of VirtualBox and comes with more seamless integration with OS X networking.

**Comment by stevensouza** [comment]
Thanks Mike. It still isn't working for me.  I am using the docker mac toolbox (VirtualBox) and the Docker Quickstart Terminal. I'll look into the other option you mentioned.  

Having said that I run:  docker run -d -p 8080:8080 jetty 

And then 'docker inspect containerid'.  I get the following.  Should  this be my ip                   "IPAddress": "172.17.0.2"?  I try http://172.17.0.2:8080, http://localhost:8080 and http://myhostip address:8080 and all say they can't find the site.  I use 'docker logs conainterid' and see that jetty is running. Any help is appreciated.

Thanks.

Here is my docker inspect output in its entirety.

```

[
    {
        "Id": "3d6df9f6643c4f425f343c554fc3785e4b5804febdbe7f53a0d5aa725aab5e4e",
        "Created": "2016-08-27T09:48:43.394604336Z",
        "Path": "/docker-entrypoint.sh",
        "Args": [
            "java",
            "-jar",
            "/usr/local/jetty/start.jar"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 16034,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2016-08-27T09:48:43.57419366Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:46310258df461f4fa61a0145a45830a9f2156598f616f5cbf4e782e8894268b4",
        "ResolvConfPath": "/mnt/sda1/var/lib/docker/containers/3d6df9f6643c4f425f343c554fc3785e4b5804febdbe7f53a0d5aa725aab5e4e/resolv.conf",
        "HostnamePath": "/mnt/sda1/var/lib/docker/containers/3d6df9f6643c4f425f343c554fc3785e4b5804febdbe7f53a0d5aa725aab5e4e/hostname",
        "HostsPath": "/mnt/sda1/var/lib/docker/containers/3d6df9f6643c4f425f343c554fc3785e4b5804febdbe7f53a0d5aa725aab5e4e/hosts",
        "LogPath": "/mnt/sda1/var/lib/docker/containers/3d6df9f6643c4f425f343c554fc3785e4b5804febdbe7f53a0d5aa725aab5e4e/3d6df9f6643c4f425f343c554fc3785e4b5804febdbe7f53a0d5aa725aab5e4e-json.log",
        "Name": "/loving_pasteur",
        "RestartCount": 0,
        "Driver": "aufs",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "8080/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8080"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "StorageOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "BlkioIOps": 0,
            "BlkioBps": 0,
            "SandboxSize": 0
        },
        "GraphDriver": {
            "Name": "aufs",
            "Data": null
        },
        "Mounts": [],
        "Config": {
            "Hostname": "3d6df9f6643c",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/jetty/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre",
                "JAVA_VERSION=8u91",
                "JAVA_DEBIAN_VERSION=8u91-b14-1~bpo8+1",
                "CA_CERTIFICATES_JAVA_VERSION=20140324",
                "JETTY_HOME=/usr/local/jetty",
                "JETTY_VERSION=9.3.10.v20160621",
                "JETTY_TGZ_URL=https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-distribution/9.3.10.v20160621/jetty-distribution-9.3.10.v20160621.tar.gz",
                "JETTY_GPG_KEYS=B59B67FD7904984367F931800818D9D68FB67BAC \t5DE533CB43DAF8BC3E372283E7AE839CD7C58886",
                "JETTY_BASE=/var/lib/jetty",
                "TMPDIR=/tmp/jetty"
            ],
            "Cmd": [
                "java",
                "-jar",
                "/usr/local/jetty/start.jar"
            ],
            "Image": "jetty",
            "Volumes": null,
            "WorkingDir": "/var/lib/jetty",
            "Entrypoint": [
                "/docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "6125f744efa6b14e9c12585782c177dc1183ff7fc3ce7ae4f39434212505e72c",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "8080/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8080"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/6125f744efa6",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "164f43e0b887095652f7d5c74254cfe48b8b18dcc2c55daf64d90e711ec86540",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "02aaca8e9e05c480af1563854bee6360b7fbf521dbe801bc616b4959ffead8e1",
                    "EndpointID": "164f43e0b887095652f7d5c74254cfe48b8b18dcc2c55daf64d90e711ec86540",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02"
                }
            }
        }
    }
]

```

**Comment by stevensouza** [comment]
Ok, Mike thanks for the tip to install 'Docker for Mac'. I installed it and jetty worked the first time I ran it.  Not sure what the problem was with using Docker Toolbox and Virtualbox, but it is working now so thanks much!

Steve

**Comment by stevensouza** [comment]
Ok, still a question.  I run the following command and I can access jetty with http://localhost:8080 - docker run -d -p 8080:8080 -p 8443:8443 jetty

But if I run the following and use 'docker inspect containerid' to get my IP address that doesn't work?: docker run -d jetty

Should it? What is the best way to get my container ip?

**Comment by md5** [comment]
You generally don't care about your container IP address. It's really only
used for talking between containers.

For that purpose, you probably want to look into the “docker network”
functionality which will allow inter-container communication by name. See
https://docs.docker.com/engine/userguide/networking/

You'll also probably come across documentation for the legacy “--link”
functionality and for the newer “docker service” functionality in Docker
1.12, but the networking guide is an easier place to start. It's also worth
noting that Docker Compose creates a user-defined bridge network between
containers in the same compose file by default.

**Comment by stevensouza** [comment]
Ok, thanks again that makes sense.  Then I am up and running for now.  Have a great weekend!

**Comment by md5** [comment]
:metal:
