### ISSUE TITLE
How to configure logback-access

### ISSUE THREAD

**Issue by bpogrebi** [appropriate/docker-jetty#54]
Hi, I have a problem getting access logs using logback. I was able to correctly get application logs by adding my logback.xml to  $JETTY_BASE/resources. 
Added logback-access.xml to $JETTY_BASE/resources and also added logback-access to "--modules"
Any help is appreciated.

**Comment by joakime** [comment]
This issue has been moved to the new Official Eclipse Jetty Docker repository.

See https://github.com/eclipse/jetty.docker/issues/5
