### ISSUE TITLE
Provide Jetty-images with JDK instead of JRE

### ISSUE THREAD

**Issue by SchulteDev** [appropriate/docker-jetty#61]
Hi,

thanks for providing docker-Jetty-images.
In my use case, I do not only want to use Jetty, I have to use JDK (instead of JRE), too¹. 
It would be great, if you could provide additional docker-Jetty-images, which contain JDK instead of JRE.

¹ 
In special: Within my docker-image, I want to be able to use [v8](https://developers.google.com/v8/). And I want to have [Alpine](https://hub.docker.com/_/alpine/) as base image. Because of Alpine, I have to compile v8 on my own, needing JDK at this point, for details see https://github.com/tarent/openjdk-alpine-j2v8. So I want Jetty, Alpine, and am needing JDK for compiling v8. 
I want to adapt the approach of tarent/openjdk-alpine-j2v8 (which extends openjdk:8-jdk-alpine) to the Jetty docker image. For this, I am "missing" jetty:jdk8-alpine.

**Comment by gregw** [comment]
So firstly, can you explain your use-case a bit more for why you need the JDK rather than JRE? Assuming a reasonable answer to that, I think a better approach may be to adopt an approach where the one maven module is parameterized so the Dockerfile is templated out with either FROM openjdk-jreX or FROM openjdk-jdkX

**Comment by SchulteDev** [comment]
Updated desciption.

**Comment by md5** [comment]
I think you should be able to put this in your Dockerfile to install the extra JDK bits for Alpine:

```Dockerfile
FROM jetty:9.4-alpine
RUN apk add --no-cache openjdk8="$JAVA_ALPINE_VERSION"
```

The `openjdk8` package in Alpine depends on `openjdk8-jre` and adds the extra files and dependencies. The situation with Debian is analogous.

**Comment by SchulteDev** [comment]
Thanks for your suggestion, I will have a try. Feedback probably next Monday.

**Comment by md5** [comment]
Sure thing. I'm going to close this issue. We can reopen it if my suggestion doesn't work. FYI, I updated the Dockerfile snippet to have the Alpine `FROM` image.
