### ISSUE TITLE
support arm64 architecture

### ISSUE THREAD

**Issue by longquan7** [appropriate/docker-jetty#69]
I use the docker-jetty/9.4-jre8/Dockerfile to build image on arm64 architecture and successed,so I think we can add it to support arm64 architecture.

**Comment by md5** [comment]
@longquan7 I'm going to close this in favor of #68. Would you mind commenting on that issue to provide more information on your `Dockerfile` and command/configuration you used to run your container?

As I mentioned in that issue, the main things I'm concerned about testing on ARM are whether the `setuid` module works and whether other modules that leverage native libraries (like UNIX socket support) work as expected.
