### ISSUE TITLE
hope docker jetty version update to 9.4.7.v20170914

### ISSUE THREAD

**Issue by iwangxiaodong** [appropriate/docker-jetty#75]
https://store.docker.com/images/jetty

now is 9.4.6.v20170531

hope docker jetty version update to 9.4.7.v20170914

Thanks！

**Comment by md5** [comment]
See the discussion in #73. I don't think 9.4.7 will be pushed to Docker Hub, but 9.4.8 should be coming soon.

**Comment by iwangxiaodong** [comment]
Okey! 
I See!
