### ISSUE TITLE
JAVA_OPTIONS not working

### ISSUE THREAD

**Issue by mkrogh** [appropriate/docker-jetty#76]
It would seem with the latest release of jetty:9-alpine and jetty:latest `JAVA_OPTIONS` set via environment variable is not working.

Simple test case:
```
docker run --rm --name jettymem -ti -e JAVA_OPTIONS=-Xmx1G jetty:latest
```

Check command run with `docker top jettymem`, the -Xmx1G is not present even though you can see it is set with `docker exec -ti jettymem sh -c ' echo "$JAVA_OPTIONS" '`

**Comment by dylanbehetre** [comment]
I have exactly the same issue with the jetty:9.4.7-jre8-alpine version

**Comment by md5** [comment]
I have a proposed fix at https://github.com/appropriate/docker-jetty/pull/78

@mkrogh @dylanBehetre Can you test it out?

**Comment by gregw** [comment]
@md5 tested with 
```
docker run -it --rm -e JAVA_OPTIONS=-verbose jetty:9.4-jre8
```
works for me !
