### ISSUE TITLE
Can't modify files in container anymore when using jetty:latest as Baseimage for Dockerfile.

### ISSUE THREAD

**Issue by tarator** [appropriate/docker-jetty#77]
I'm using `jetty:latest` as Baseimage in my Dockerfile (`FROM jetty:latest`)

I used to modify some parts within the Container with statements in my Dockerfile like:

    RUN rm -f /etc/localtime && ln -snf /usr/share/zoneinfo/$TIMEZONE /etc/localtime && echo $TIMEZONE > /etc/timezone

    RUN apt-get update && \
        apt-get -y upgrade && \
        apt-get -y install foo bla && \
        apt-get clean
    RUN mkdir /somedir

Since the latest version of the Image I get an "permission denied" error when trying to run any of this commands.

**Comment by md5** [comment]
@tarator You'll need to switch to `USER root` and then switch back to `USER jetty` to make this work. This change happened as a result of #72

**Comment by tarator** [comment]
Thanks @md5 ! Adding the statement `USER root` before, and `USER jetty` after the the modifying statements does the trick!
