### ISSUE TITLE
i install but how to execute remote

### ISSUE THREAD

**Issue by fthamura** [appropriate/docker-jetty#8]
i success install the jetty docker 

docker run -d -p 8888:8080 jetty:9

but when try to access to ip:8080, it wont work

any idea?

**Comment by md5** [comment]
With that command, you're actually mapping port `8888` outside the container to port `8080` inside.

Try using `http://IP:8888/` (or use `-p 8080:8080`, `-p 80:8080`, etc).

**Comment by md5** [comment]
@fthamura Did you get this working? Let me know I can close this issue.

**Comment by md5** [comment]
I'm going to close this issue. Feel free to reopen if you feel that I've closed it in error.
