### ISSUE TITLE
Jetty 9.3-jre8 uses Java version 10 

### ISSUE THREAD

**Issue by daanottink** [appropriate/docker-jetty#87]
All the latest Jetty 9.3-jre8 use Java 10. Alpine seems to work

**Comment by viktorsteinwand** [comment]
I've found this issue now as well. However, it looks like all latest JRE8 non Apline images have the same issue:

```
docker-compose.yml content:
...
    jetty:
        image: jetty:9.3-jre8
        ...

➜  docker-compose exec jetty java -version
openjdk version "10" 2018-03-20
OpenJDK Runtime Environment (build 10+46-Debian-2)
OpenJDK 64-Bit Server VM (build 10+46-Debian-2, mixed mode)
```

Using the alpine image did help in my case:

```
docker-compose.yml content:
...
    jetty:
        image: jetty:9.3-jre8-alpine
        ...

➜  docker-compose exec jetty java -version
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (IcedTea 3.6.0) (Alpine 8.151.12-r0)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
```

**Comment by daanottink** [comment]
@viktorsteinwand downgrading to 9.3.21-jre8 worked for us

**Comment by tianon** [comment]
Looks like this is related to
https://github.com/docker-library/openjdk/issues/180. 😞

**Comment by tianon** [comment]
Just to update further, we found the source of the issue, and are re-doing builds as quickly as the server can get through them. :heart:

**Comment by tianon** [comment]
This should have been resolved for several days now. :smile: :+1:
