### ISSUE TITLE
Remove link to https://wiki.eclipse.org/Jetty/Howto/Deploy_Web_Applications

### ISSUE THREAD

**Issue by md5** [appropriate/docker-jetty#9]
A user left a comment on the Docker Hub that the docs at https://wiki.eclipse.org/Jetty/Howto/Deploy_Web_Applications contradict what we have in the `README.md`. It looks like that wiki page hasn't been updated since 2013, so that link should either be removed or replaced with a link that points to officially maintained documentation.

**Comment by chadmichael** [comment]
I think the wiki information worked, while the README.md seems incorrect.  Seems like it might be due to the fact that the README.md is the same for all the various TAG/Versions of the image, but that information doesn't apply across those versions equally.  In my case, I'm using one of the older jetty7 images . . . and the README info is incorrect in that case.

**Comment by md5** [comment]
Jetty 7 is EOL'd upstream, so it is no longer supported here. I do have [a branch](https://github.com/md5/docker-jetty/tree/eol/jetty-7) for Jetty 7, but it doesn't have a real `README.md` since that lives in https://github.com/docker-library/docs. The README should only be expected to work for the currently supported versions, which means Jetty 9.

**Comment by chadmichael** [comment]
That's fair.  I was impressed to find an image of an older version in the first place.

**Comment by md5** [comment]
When I get back around to working on this issue, I'll keep in mind the EOL'd Jetty 7 and 8 and try to make it clearer what works and what doesn't.

Thanks for the report! :+1:

**Comment by md5** [comment]
I've opened a PR to update the `jetty` docs: https://github.com/docker-library/docs/pull/226

**Comment by md5** [comment]
I've also updated the `README.md` on the `eol/jetty-7` and `eol/jetty-8` branches to indicate the end-of-life status of those versions.

cf. 29db2952567e966368add1e82ad22ece84f783e1 and 3e97174ba819fe5ae4f55bf1664d6d479119e4d2

**Comment by md5** [comment]
The docs have been updated to hopefully make deployment clearer, so I'm going to close this issue. Please reopen if I've overlooked something.
