### ISSUE TITLE
Any plans for jre11 ?

### ISSUE THREAD

**Issue by s17t** [appropriate/docker-jetty#98]
As the title. Are there plans for docker-jetty on jre 11 ?

**Comment by gregw** [comment]
Latest jetty-9.4 releases are jre 11 ready, so I guess we should!  Hopefully soon...
We will also have a jetty-10 release early in the new year that is fully JPMSized

**Comment by gregw** [comment]
I've created a PR #99 for this (along with upgrade to 9.4.14) and initial quick look seams OK.   @s17t could you give this branch a test?
I have also left out the alpine distribution for jre11 as I'm not sure if that makes sense anymore.

**Comment by s17t** [comment]
Hello and thank you. I am testing right now and in the next days. I had to work around gid and uid of jetty user: in the alpine distro jetty user has 100:101 uid, gid but in debian it has 1000:1001. 

Nothing that can be fixed using usermod/groupmod and chown accordingly. I would state this somewhere in a changelog if the alpine tag will be dropped.

**Comment by s17t** [comment]
> I'm not sure if that makes sense anymore.

It would made sense for sure since the image size is more than the double now. They are debating about alpine/openjdk11 issue in docker-library/openjdk/issues/211

**Comment by md5** [comment]
#99 is closed, so Jetty 9.4 with JRE 11 will be available shortly. This is limited to Debian-based images, since Alpine-based images for JRE 11 don't exist yet.
